### ISSUE TITLE
pnpm create vite-plugin-web-extension error occurred

### ISSUE THREAD

**Issue by Air-Smile** [aklinker1/vite-plugin-web-extension#120]
FetchError: fetch failed (https://raw.githubusercontent.com/aklinker1/vite-plugin-web-extension/main/packages/create-vite-plugin-web-extension/templates/templates.json)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (file:///Users/airsmile/Library/pnpm/store/v3/tmp/dlx-5160/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)
    at async $fetch2 (file:///Users/airsmile/Library/pnpm/store/v3/tmp/dlx-5160/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)
    at async resolveOptions (file:///Users/airsmile/Library/pnpm/store/v3/tmp/dlx-5160/node_modules/.pnpm/create-vite-plugin-web-extension@1.0.3/node_modules/create-vite-plugin-web-extension/dist/index.js:185:23)
    at async initProject (file:///Users/airsmile/Library/pnpm/store/v3/tmp/dlx-5160/node_modules/.pnpm/create-vite-plugin-web-extension@1.0.3/node_modules/create-vite-plugin-web-extension/dist/index.js:134:20)

Failed to load templates from url (https://raw.githubusercontent.com/aklinker1/vite-plugin-web-extension/main/packages/create-vite-plugin-web-extension/templates/templates.json).
See above error.
 ERROR  Command failed with exit code 1: create-vite-plugin-web-extension

**Comment by aklinker1** [comment]
Interesting, I think github was just down? Can you try it again? I can load the URL just fine right now.
