### ISSUE TITLE
pnpm create vite-plugin-web-extension error occurred

### ISSUE THREAD

**Issue by jackchang1025** [aklinker1/vite-plugin-web-extension#206]
FetchError: [GET] "https://raw.githubusercontent.com/aklinker1/vite-plugin-web-extension/main/packages/create-vite-plugin-web-extension/templates/templates.json": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (file:///root/.npm/_npx/628be3a17733739d/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:231:14)
    ... 2 lines matching cause stack trace ...
    at async initProject (file:///root/.npm/_npx/628be3a17733739d/node_modules/create-vite-plugin-web-extension/dist/index.js:134:20) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13178:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (file:///root/.npm/_npx/628be3a17733739d/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:222:26)
      at async $fetchRaw2 (file:///root/.npm/_npx/628be3a17733739d/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:231:14)
      at async $fetch2 (file:///root/.npm/_npx/628be3a17733739d/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
      at async resolveOptions (file:///root/.npm/_npx/628be3a17733739d/node_modules/create-vite-plugin-web-extension/dist/index.js:185:23)
      at async initProject (file:///root/.npm/_npx/628be3a17733739d/node_modules/create-vite-plugin-web-extension/dist/index.js:134:20) {
    [cause]: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout (node:internal/deps/undici/undici:2331:28)
        at node:internal/deps/undici/undici:2283:50
        at Immediate._onImmediate (node:internal/deps/undici/undici:2315:13)
        at process.processImmediate (node:internal/timers:483:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
}

**Comment by aklinker1** [comment]
https://github.com/aklinker1/vite-plugin-web-extension/issues/120#issuecomment-1607614376
