### ISSUE TITLE
No crome installations fount 

### ISSUE THREAD

**Issue by TomasRas** [aklinker1/vite-plugin-web-extension#209]
### Summary

Starting Vite i`am getting error 'No Chrome installations found.' but it is there.

### Reproduction

run vite dev 

### Environment

Wn 11 

```
Paste output here
```at async ChromiumExtensionRunner.run (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/web-ext-run/lib/extension-runners/chromium.js:55:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/web-ext-run/lib/extension-runners/index.js:67:5)
    at async run (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/web-ext-run/lib/cmd/run.js:182:3)
    at async Object.openBrowser (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/vite-plugin-web-extension/dist/index.js:886:16)
    at async openBrowser (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/vite-plugin-web-extension/dist/index.js:1151:5)
    at async buildExtension (file:///C:/my-projects/browser-assistant/browser-assistant/node_modules/vite-plugin-web-extension/dist/index.js:1190:7) {
  message: 'No Chrome installations found.',
  code: 'ERR_LAUNCHER_NOT_INSTALLED'

**Comment by aklinker1** [comment]
See https://vite-plugin-web-extension.aklinker1.io/guide/configure-browser-startup.html
